### PR TITLE
Added config setting for custom timeout after creating folder before moving email to it

### PR DESCRIPTION
**Pull request by adamkerz**
Config setting of: extensions.nostalgy.timeout_after_creating_folder, no addition to the preferences dialog as I'm not an extension developer and have no dev environment to build and test.

### CODE REVIEW

**Comment by adamkerz** [comment]
Any thoughts on this @alainfrisch? I'm just going through the process of making the same patch to the extension (unzipping the xpi and then the jar within that, making the change and zipping them all back up) due to an update, which is a bit painful. Also, surely it would be useful to others too.

**Comment by alainfrisch** [comment]
Ok with the change, but can you rename the property to "delay_after_creating_folder"?

**Comment by adamkerz** [comment]
No problem, good to go. Thanks heaps!

**Comment by adamkerz** [comment]
@alainfrisch Hi Alain, I know this probably isn't a high priority for you, but I just updated Nostalgy and it broke my folder creation again. Is there anything more you need on this PR for it to be merged?

**Comment by alainfrisch** [comment]
Sorry for the delay!  This will be included in the next version.

**Pull request merged**
